jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          command: |
            apt-get update && apt-get install -y unzip wget
            wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
            unzip -d /usr/local/bin terraform_0.11.11_linux_amd64.zip
            terraform fmt -check=true
version: 2
